DATABASE_HOST=${DB_HOST}
DATABASE_NAME=${DB_NAME}
DATABASE_USER=${DB_USER}
DATABASE_PASSWORD=${DB_PASSWORD}
DATABASE_PORT=${DB_PORT}


S3_BUCKET_NAME=${S3_BUCKET_NAME}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_DEFAULT_REGION=eu-central-1

DEBUG=True
CORS_ORIGIN_WHITELIST=http://localhost:8080,http://127.0.0.1:8080
ALLOWED_HOSTS=*
CORS_ALLOWED_ORIGIN_REGEXES=^http://.+\\.localhost:8080\$
